---
# tasks file for roles/cli-utils

# "screen" package is not available on RHEL 9
# https://access.redhat.com/solutions/4136481
# whereas we can use epel to install it on
# Rocky Linux 9
- name : check rocky.repo file
  stat:
    path: /etc/yum.repos.d/rocky.repo
  register: rockyrepo_name

- name: system packages | Add CRB repository for RHEL
  become: true
  ansible.builtin.command:
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms
  when: ansible_os_family == 'RedHat' and not rockyrepo_name.stat.exists

- name: system packages | install epel repo
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: rockyrepo_name.stat.exists

- name: Import a key for postgres
  ansible.builtin.rpm_key:
    state: present
    key:  https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

- name: postgres | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present


- name: system packages | cli user utils
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - bzip2
      - tmux
      - zsh
    state: present
  when: ansible_os_family == 'RedHat'
