---
# tasks file for roles/cli-utils

# "screen" package is not available on RHEL 9
# https://access.redhat.com/solutions/4136481
# whereas we can use epel to install it on
# Rocky Linux 9
- name : check rocky.repo file
  stat:
    path: /etc/yum.repos.d/rocky.repo
  register: rockyrepo_name

- name: Import a key for epel
  ansible.builtin.rpm_key:
    state: present
    key:  https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: epel | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: system packages | cli user utils
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - bzip2
      - screen
      - tmux
      - zsh
    state: present
  when: ansible_os_family == 'RedHat'
