---
# tasks file for roles/cli-utils

- name: system packages | cli user utils
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - bzip2
      - screen
      - tmux
      - zsh
    state: present
